/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package displayprice;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void appDisplayItemWithPrice() {
        App classUnderTest = new App();
        assertEquals("App should return item along with price", String.valueOf("The price for item banana is 2"), classUnderTest.getPriceLabel("banana",2));
    }
}
